dist: trusty
language: python

python:
  - "2.7"

env:
  global:
    - ENCRYPTION_LABEL: "19eabc20b015"
    - COMMIT_AUTHOR_EMAIL: "hosting@tvstreams.xyz"

script:
  - bash .github/build.sh

branches:
  only:
    - master
